[package]
name = "coral_chords"
version = "0.1.0"
edition = "2024"

[dependencies]
mpris = "2.0.1"
opener = "0.8.2"
ug-scraper = "0.2.1"

[dependencies.confy]
version = "1.0.0"
features = ['yaml_conf']
default-features = false

[dependencies.serde]
version = "1.0.219"
features = ["derive"]

[dependencies.iced]
version = "0.13.1"
features = ["tokio"]
