[package]
name = "Coral-Chords"
description = "Chord downloading from Ultimate Guitar and synching with Spotify"
repository = "https://github.com/Lich-Corals/coral-chords/"
readme = "README.md"
keywords = ["GUI", "guitar", "music", "Spotify", "ultimate-guitar"]
categories = ["multimedia"]
version = "0.4.1"
edition = "2024"
license = "AGPL-3.0-or-later"

exclude = [".gitignore", ".github/*", "latex/*", "coral-chords.desktop", "rustfmt.toml"]

[dependencies]
mpris = "2.0.1"
opener = "0.8.2"
ug-scraper = "0.2.3"

[dependencies.confy]
version = "1.0.0"
features = ['yaml_conf']
default-features = false

[dependencies.serde]
version = "1.0.219"
features = ["derive"]

[dependencies.iced]
version = "0.13.1"
features = ["tokio"]

[dependencies.e_crate_version_checker]
version = "0.1.33"
features = ["check-version"]
